### ISSUE TITLE
Störmeldungs-Mailadresse

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/fablab-android#6]
ist zur Zeit fablab@i2..., sollte kontakt@fablab sein, ist da irgendwas verauscht?

**Comment by Phyxtra** [comment]
Eigentlich müsste die Adresse im Server in der config.yml stehen.

**Comment by sedrubal** [comment]
Jup

``` yml
generalData:
    fabMail: fablab@i2.cs.fau.de
    feedbackMail: fablab@i2.cs.fau.de
    fabUrl: https://fablab.fau.de
```
